FROM alpine as builder

FROM maven:3.2-jdk-8 as build
ARG project
COPY src /usr/src/app/src  
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package


FROM openjdk:8-jre-alpine
ARG artificatid
ARG version
ARG project
ENV artifact=${artificatid}-${version}.jar

COPY --from=build /usr/src/app/target/${artifact} /usr/src/app/${artifact}
RUN chmod 755 /usr/src/app/${artifact}
 EXPOSE 8080
 #ENTRYPOINT ["sh", "-c","java"]
 ## docker build --build-arg artificatid=spring-boot-api-template --build-arg "version=0.0.1-SNAPSHOT" .

CMD java -jar /usr/src/app/$artifact
#CMD ["sh","-c","java -jar /usr/src/app/$artifact"]
#CMD ["sh", "-c", "ps", "-ef" ]
